-- =========================================
-- PURCHASES: deny-all to anon/authenticated
-- =========================================
ALTER TABLE public.purchases ENABLE ROW LEVEL SECURITY;

-- Drop any pre-existing policies (idempotent)
DROP POLICY IF EXISTS "Deny all access to purchases" ON public.purchases;
DROP POLICY IF EXISTS "No public read of purchases" ON public.purchases;
DROP POLICY IF EXISTS "No public insert of purchases" ON public.purchases;
DROP POLICY IF EXISTS "No public update of purchases" ON public.purchases;
DROP POLICY IF EXISTS "No public delete of purchases" ON public.purchases;

-- Explicit deny policies for anon and authenticated roles.
-- The service_role used by edge functions bypasses RLS, so the
-- backend can still insert purchases and read them when needed.
CREATE POLICY "No public read of purchases"
ON public.purchases
FOR SELECT
TO anon, authenticated
USING (false);

CREATE POLICY "No public insert of purchases"
ON public.purchases
FOR INSERT
TO anon, authenticated
WITH CHECK (false);

CREATE POLICY "No public update of purchases"
ON public.purchases
FOR UPDATE
TO anon, authenticated
USING (false)
WITH CHECK (false);

CREATE POLICY "No public delete of purchases"
ON public.purchases
FOR DELETE
TO anon, authenticated
USING (false);

-- Revoke any direct table privileges from public roles as defense-in-depth
REVOKE ALL ON public.purchases FROM anon;
REVOKE ALL ON public.purchases FROM authenticated;

-- =========================================
-- STORAGE: lock down legal-documents bucket
-- =========================================
-- Ensure bucket stays private
UPDATE storage.buckets SET public = false WHERE id = 'legal-documents';

-- Drop any prior policies for this bucket (idempotent)
DROP POLICY IF EXISTS "Deny anon access to legal-documents" ON storage.objects;
DROP POLICY IF EXISTS "Deny authenticated access to legal-documents" ON storage.objects;
DROP POLICY IF EXISTS "No public select on legal-documents" ON storage.objects;
DROP POLICY IF EXISTS "No public insert on legal-documents" ON storage.objects;
DROP POLICY IF EXISTS "No public update on legal-documents" ON storage.objects;
DROP POLICY IF EXISTS "No public delete on legal-documents" ON storage.objects;

-- Block all direct access to the bucket from anon and authenticated roles.
-- Files are only served via signed URLs generated by the verify-payment
-- edge function (which uses the service_role and bypasses RLS).
CREATE POLICY "No public select on legal-documents"
ON storage.objects
FOR SELECT
TO anon, authenticated
USING (bucket_id = 'legal-documents' AND false);

CREATE POLICY "No public insert on legal-documents"
ON storage.objects
FOR INSERT
TO anon, authenticated
WITH CHECK (bucket_id = 'legal-documents' AND false);

CREATE POLICY "No public update on legal-documents"
ON storage.objects
FOR UPDATE
TO anon, authenticated
USING (bucket_id = 'legal-documents' AND false)
WITH CHECK (bucket_id = 'legal-documents' AND false);

CREATE POLICY "No public delete on legal-documents"
ON storage.objects
FOR DELETE
TO anon, authenticated
USING (bucket_id = 'legal-documents' AND false);